###################################
##              授权模块
###################################
server:
  #  servlet:
  #    context-path: /sso
  port: 8899


spring:
  application:
    name: auth
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssms_sso_auth?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver


# 日志输出sql语句
logging:
  level:
    #    org.springframework.security: debug
    com.baomidou.mybatisplus.core: info
    com:
      wang:
        sso:
          modules:
            sys:
              dao: debug # 打印sql
          core:
            -*: debug # security调试


mybatis-plus:
  #  mapper-locations: classpath*:mappings/*/*.xml # xml文件配置，已在MyBatisConfig中配置
  check-config-location: true # 启动时是否检查mybatis xml文件存在，默认不检查
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
  global-config:
    refresh: true # 是否自动刷新 Mapper 对应的 XML 文件，开发时设置为是
    db-config:
      db-type: mysql # 数据库类型，不配置时会自动按照url连接获取
      id-type: id_worker_str # 全局主键配置，字符串类型的id_worker
#      logic-delete-value: 1 # 逻辑删除值，逻辑删除有效，与mp配置一样时，该配置可无
#      logic-not-delete-value: 0 # 逻辑未删除值，与mp配置一样时，该配置可无
      #      table-prefix: sys_ # 表名前缀，配置这个之后可以把项目微服务化，每个模块一个数据库，对应里面的表前缀
      table-underline: true # 表名是否使用下划线命名
